- name: rebuild configuration
  shell: ls /etc/nginx/tools/
  register: tools
  notify: write configuration

- name: write configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: systemctl
  shell: systemctl daemon-reload

- name: aggregate-hosts
  shell: cat /etc/ansible/hosts.d/*.ini > /etc/ansible/hosts
